### ISSUE TITLE
Can't find title of song?

### ISSUE THREAD

**Issue by jazware** [jakiestfu/off-the-rip#10]
I've got this issue here for some reason

```
/var/www/test$ otr dl 'https://soundcloud.com/dimmakrecords/the-chainsmokers-selfie-botnek-remix-1' music
LOG: Sniffing network...
/usr/lib/node_modules/off-the-rip/lib/downloader.js:41
    var audio_dest = path.join(dest, info.title + '.mp3');
                                         ^
TypeError: Cannot read property 'title' of undefined
    at /usr/lib/node_modules/off-the-rip/lib/downloader.js:41:42
    at ChildProcess.exithandler (child_process.js:758:5)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
```

Is anyone else having any problems like this or might it be my firewall configurations?

**Comment by lightyrs** [comment]
@ericvolp12 I'm seeing this sometimes as well.  I don't have my logs right now but I'll post tomorrow.

**Comment by jakiestfu** [comment]
Looking into this now

**Comment by jakiestfu** [comment]
This works fine for me. The problem isn't that title is missing, it's that phantom is erroring out. You can see that the only intended log is guarded by a check for `info.title`

https://github.com/jakiestfu/off-the-rip/blob/master/lib/sniff.js#L20

What needs to happen is issue #2, this will give us more insight into some of the errors that are happening. I will work on that right now. In the meantime, I will close this issue until we have better means to debug what's happening. Stay tuned!

**Comment by jakiestfu** [comment]
@ericvolp12 @lightyrs Update your module to 0.3.5, there is more verbose logging and there should be error catching which will help debug your issues.

**Comment by lightyrs** [comment]
Thanks @jakiestfu.
