### ISSUE TITLE
Error writing ID3 tags

### ISSUE THREAD

**Issue by JPLeBreton** [jakiestfu/off-the-rip#17]
This appears to happen for every soundcloud link I've tried thus far.
system: Antergos (Arch) Linux, x86_64, kernel 4.1, Python 3.4

log:

```
LOG: Downloading Artwork...
LOG: Resolving MP3 URI...
LOG: Downloading MP3...
LOG: Writing ID3 Tags...
eyeD3 --remove-all "/tmp/audio-1438368745712.mp3"

Error: Command failed: /bin/sh -c env eyeD3 --remove-all "/tmp/audio-1438368745712.mp3"
Uncaught exception: ord() expected string of length 1, but int found

eyed3:ERROR: ord() expected string of length 1, but int found
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/eyed3/main.py", line 284, in <module>
    retval = mainFunc(args, config)
  File "/usr/lib/python3.4/site-packages/eyed3/main.py", line 52, in main
    fs_encoding=args.fs_encoding)
  File "/usr/lib/python3.4/site-packages/eyed3/utils/__init__.py", line 125, in walk
    handler.handleFile(os.path.abspath(path))
  File "/usr/lib/python3.4/site-packages/eyed3/plugins/classic.py", line 422, in handleFile
    super(ClassicPlugin, self).handleFile(f, tag_version=parse_version)
  File "/usr/lib/python3.4/site-packages/eyed3/plugins/__init__.py", line 174, in handleFile
    self.audio_file = core.load(f, *args, **kwargs)
  File "/usr/lib/python3.4/site-packages/eyed3/core.py", line 90, in load
    return mp3.Mp3AudioFile(path, tag_version)
  File "/usr/lib/python3.4/site-packages/eyed3/mp3/__init__.py", line 165, in __init__
    core.AudioFile.__init__(self, path)
  File "/usr/lib/python3.4/site-packages/eyed3/core.py", line 245, in __init__
    self._read()
  File "/usr/lib/python3.4/site-packages/eyed3/mp3/__init__.py", line 183, in _read
    self._info = Mp3AudioInfo(file_obj, mp3_offset, self._tag)
  File "/usr/lib/python3.4/site-packages/eyed3/mp3/__init__.py", line 95, in __init__
    if not self.xing_header.decode(mp3_frame):
  File "/usr/lib/python3.4/site-packages/eyed3/mp3/headers.py", line 312, in decode
    version = (ord(frame[1]) >> 3) & 0x1
TypeError: ord() expected string of length 1, but int found

    at ChildProcess.exithandler (child_process.js:751:12)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
```

**Comment by mlissner** [comment]
You need to upgrade eyeD3: https://github.com/nicfit/eyeD3/issues/12
