### ISSUE TITLE
Installation of dependencies across linux and windows

### ISSUE THREAD

**Issue by jakiestfu** [jakiestfu/off-the-rip#4]
Looking at `brew install eyeD3 phantomjs rtmpdump`

Solution is a bash script like the following:

``` sh
if [ isLinux ] ; then
  apt-get eyeD3 phantomjs rtmpdump
elseif [isWindows ] ; then
  # ?
elseif [ isMac ] ; then
  brew install eyeD3 phantomjs rtmpdump
fi
```

**Comment by ghost** [comment]
I am having issues installing on Ubuntu because of the brew dependency (I think)

**Comment by jakiestfu** [comment]
Do these dependencies exist with `apt-get` ?

**Comment by ghost** [comment]
I don't think so; I was able to install all three with apt-get; but it still throws

> off-the-rip@0.3.2 preinstall /usr/lib/node_modules/off-the-rip
> ./scripts/pre-install.sh

./scripts/pre-install.sh: line 3: brew: command not found

**Comment by ghost** [comment]
Is there a way to throw an argument to it so it skips the pre-install script?

**Comment by jakiestfu** [comment]
@nichbarry Not currently. I've updated the initial description of this issue with pseudo code. This is the solution we should strive for as opposed to suppressing brew install issues. Is this something you can help with?

**Comment by ghost** [comment]
I see; will see what I can do; kind of am with node.js; would need to figure how to npm install from local repo...

**Comment by jakiestfu** [comment]
@nichbarry Let me try something first, don't want to waste your time. Hang tight.

**Comment by jakiestfu** [comment]
@nichbarry Can you try a clean install of this and tell me if it worked for you? What OS are you using?

**Comment by nichbarry** [comment]
strange messages; how do I get a clean install?

Asks me for sudo password for nobody...

Thank you for your support and efforts!

sudo npm i -g off-the-rip
/
> off-the-rip@0.3.4 preinstall /usr/lib/node_modules/off-the-rip
> ./scripts/pre-install.sh

Top hits for "install" "phantomjs"
————————————————————————————————————————————————————————————————————————————————
npm help install                                                      install:83
npm help folders                                                      install:42
npm help scripts                                                      install:41
npm help package.json                                                 install:34
npm help config                                                       install:34
npm help shrinkwrap                                                   install:28
npm help faq                                                          install:22
npm help npm                                                          install:20
npm help update                                                       install:14
npm help developers                                                   install:14
npm help removing-npm                                                 install:14
npm help index                                                        install:13
npm help scope                                                        install:12
npm help uninstall                                                    install:11
npm help dist-tag                                                      install:7
npm help tag                                                           install:7
npm apihelp install                                                    install:7
npm apihelp uninstall                                                  install:6
npm help link                                                          install:5
npm apihelp ls                                                         install:5
npm help edit                                                          install:5
npm help publish                                                       install:5
npm help ls                                                            install:4
npm apihelp npm                                                        install:4
npm help rm                                                            install:4
npm apihelp edit                                                       install:4
npm apihelp link                                                       install:3
npm help explore                                                       install:3
npm help build                                                         install:3
npm help bundle                                                        install:3
npm help disputes                                                      install:2
npm apihelp deprecate                                                  install:2
npm help outdated                                                      install:2
npm help rebuild                                                       install:2
npm help cache                                                         install:2
npm apihelp explore                                                    install:2
npm apihelp update                                                     install:1
npm apihelp pack                                                       install:1
npm help bin                                                           install:1
npm apihelp publish                                                    install:1
npm help npmrc                                                         install:1
npm apihelp rebuild                                                    install:1
npm help pack                                                          install:1
npm apihelp tag                                                        install:1
npm help dedupe                                                        install:1
npm help deprecate                                                     install:1
npm help run-script                                                    install:1
npm apihelp test                                                       install:1
npm apihelp bin                                                        install:1
npm help test                                                          install:1
npm help semver                                                        install:1
————————————————————————————————————————————————————————————————————————————————
(run with -l or --long to see more context)
[sudo] password for nobody:

**Comment by ghost** [comment]
Okay I have it running in Ubuntu 14.04; successfully goes out and gets it (I think) but does not show up in target folder...

Getting a memory error phantomjs: Error in `/usr/lib/phantomjs/phantomjs': double free or corruption (out):

Have you seen this?

**Comment by jakiestfu** [comment]
wat

I've never seen that before. I'm working on better phantom logging so that may help, hang tight with me @nichbarry, I'm working on a mac so it's difficult to test for linux, even with Vagrant.

**Comment by ghost** [comment]
For sure; looks like you have to install phantom from source for linux according to their website; will let you know if that helps

**Comment by jakiestfu** [comment]
@nichbarry Wait, I think I found a bug: https://github.com/jakiestfu/off-the-rip/blob/master/scripts/pre-install.sh#L4

That should be `-g`, you can install later versions of phantomjs that way. Give that a try, I'll be committing a fix soon

**Comment by ghost** [comment]
okay now....after -g install

/home/[MYUSERNAME]/node_modules/off-the-rip/lib/downloader.js:41
    var audio_dest = path.join(dest, info.title + '.mp3');
                                         ^
TypeError: Cannot read property 'title' of undefined
    at /home/nicholas/node_modules/off-the-rip/lib/downloader.js:41:42
    at ChildProcess.exithandler (child_process.js:742:7)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Process.ChildProcess._handle.onexit (child_process.js:1087:5)

**Comment by jakiestfu** [comment]
Working on issue #2

**Comment by jakiestfu** [comment]
@nichbarry `npm uninstall -g off-the-rip` and try installing again. Logging is more verbose which might help me debug your issues.

**Comment by ghost** [comment]
Now..

ERROR { [Error: Command failed: /bin/sh -c phantomjfs /home/[MYUSERNAME]/off-the-rip/lib/sniff.js https://soundcloud.com/celestial-trax/pheliac
/bin/sh: 1: phantomjfs: not found
]
  killed: false,
  code: 127,
  signal: null,
  cmd: '/bin/sh -c phantomjfs /home/nicholas/off-the-rip/lib/sniff.js https://soundcloud.com/celestial-trax/pheliac' }
ERROR /bin/sh: 1: phantomjfs: not found

**Comment by jakiestfu** [comment]
Dude I'm such an ass, I'm going too fast. Repeat those steps again and update to 0.3.6, sorry mate.

**Comment by ghost** [comment]
No worries!

**Comment by ghost** [comment]
Okay now it looks like it does not get past Sniffing network...
Just takes me back to the command line after LOG: Sniffing network...

**Comment by ghost** [comment]
Okay so I found the mp3 previously downloaded in my tmp folder; so looks like it was working previously just not delivering the final contents to the folder specified..

**Comment by jakiestfu** [comment]
@nichbarry I was able to repro a bunch of issues and I _hope_ things are better. 1. You shouldn't (in theory) have to have `phantomjs` installed globally anymore, so feel free to uninstall. 2. The `phantomjs` binary being used is installed relatively from `npm`

The version is 0.3.10

**Comment by ghost** [comment]
How do I uninstall phantomjs? It was basically working earlier, just wasn't delivering from tmp, so def had some success but cannot get it back to that point yet!

~/off-the-rip$ sudo npm install
npm WARN package.json off-the-rip@0.3.10 No license field.
npm WARN cannot run in wd off-the-rip@0.3.10 ./scripts/pre-install.sh (wd=/home/nicholas/off-the-rip)
/

> phantomjs@2.0.0-alpha1 install /home/[username]/off-the-rip/node_modules/phantomjs
> node install.js

Looks like an `npm install -g`; unable to check for already installed version.
There is no prebuilt binary for your platform: linux x64 3.16.0-41-generic
You should install phantomjs from source, put the binary on your PATH, and try again
npm ERR! Linux 3.16.0-41-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v0.12.6
npm ERR! npm  v2.11.2
npm ERR! code ELIFECYCLE

npm ERR! phantomjs@2.0.0-alpha1 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the phantomjs@2.0.0-alpha1 install script 'node install.js'.
npm ERR! This is most likely a problem with the phantomjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls phantomjs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/[username]/off-the-rip/npm-debug.log

**Comment by jakiestfu** [comment]
NPM isn't meant to install non-NPM dependencies. I just updated the readme, look at the [Dependencies](https://github.com/jakiestfu/off-the-rip#dependencies) section, _then_ try an npm install. Let me know if that helped at all!

**Comment by dqbd** [comment]
Is there a necessity for a Windows script? As there isn't a pre-install.sh script anymore.
